version: "3"
services: 
  microstation:
    container_name: microstation-server
    build: .
    ports:
      - "5000:5000"
    volumes: 
      - .:/server
    environment: 
      - PYTHONUNBUFFERED=0

